### ISSUE TITLE
peanut curry

### ISSUE THREAD

**Issue by don-patterson** [don-patterson/recipes#14]
https://www.honeygheeandme.com/2012/04/crockpot-chicken-peanut-curry/
Ingredients
4 pieces chicken- boneless/skinless, breasts and/or thighs- approx 1.5 lb

1 14 oz can coconut milk (not light)

1 tsp curry powder

1 tsp red Thai curry paste

1/2 tsp honey (I prefer raw- omit for Whole30)

1/2 tsp grated ginger

1/4 tsp red pepper flakes

2 tbsp peanut, almond, or cashew butter

2 tbsp coconut aminos or tamari

1/2 cup chopped yellow onion

1/2 cup sliced red bell pepper

1 tbsp chopped basil leaves, preferably Thai

1/4 cup cilantro

1 cup snap or snow peas

salt, pepper, and lime juice, to taste (see note below)

 .

*for garnish- lime, cilantro, basil, scallions, and toasted cashews (or peanuts)

**Sriracha and/or red pepper flakes for an extra kick!

***about salt, the recipe doesn’t actually have any in it as it cooks- that’s because depending on whether you go with tamari or coconut aminos, the cut of chicken, and so forth, the flavors will vary once cooked- it will need salt, but add all that stuff (salt, pepper, lime) at the end to make sure your flavors are balanced how you like ’em.

DIRECTIONS

Mix coconut milk, curry powder, curry paste, honey,

red pepper flakes, ginger, nut butter, and coconut aminos/tamari together in Crock Pot

Slice red pepper, onion, basil, and cilantro

If using ginger, grate it too

Add it all to the sauce

Stir until well mixed

Place chicken breasts/thighs into sauce…

They should be fully immersed so that liquid covers them

Cover and cook in high for 3 1/2 – 4 hours or on low for about 5 1/2 – 6

When done, gently stir it all together- the chicken will fall apart on the spot

Throw in peas just before serving

Serve over cooked rice

Get garnishes ready…

Top the chicken with all of the goodies you want, serve with lime, and enjoy!

**Comment by deek80** [comment]
what we actually did (and turned out pretty nice)
- added all liquid ingredients to the instant pot:
  - coconut milk
  - curry powder
  - curry paste (1.5 tsp)
  - honey
  - red pepper flakes (1/2 tsp)
  - ginger (1 tbsp)
  - peanut butter (3 tbsp, could do 4)
- added 3 frozen chicken breasts
- pressure cook for 7 minutes (would try 6 next time)
- quick release
- add all remaining ingredients
- pressure cook for 3 minutes
- quick release
